name: Lint and Test on Pull Request Frontend

on: pull_request

jobs:
  frontend-commit-checks:
    runs-on: ubuntu-latest
    name: Checks before commit
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat client/.nvmrc)"
        id: nvm
      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v4
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: Install dependencies
        run: yarn
      - name: Run lint
        run: yarn lint --quiet
      - name: Run Tests
        run: yarn test
      - name: Check for changes
        run: git diff --exit-code
      - name: Comment on PR if lint fails
        if: ${{ failure() }}
        run: |
          echo "Lint checks failed. Please review and fix the issues."
          exit 1
